[package]
name = "simdict"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4"
slint = "1.14"
anyhow = "1.0"
env_logger = "0.11"
urlencoding = "2.1"
reqwest = { version = "0.13", features = ["blocking"] }

[build-dependencies]
slint-build = "1.14"
